# Generated by Django 2.2 on 2020-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(default='email@email.com', max_length=45),
        ),
        migrations.AddField(
            model_name='address',
            name='first_name',
            field=models.CharField(default='test', max_length=45),
        ),
        migrations.AddField(
            model_name='address',
            name='last_name',
            field=models.CharField(default='test', max_length=45),
        ),
    ]
